# Generated by Django 4.1.1 on 2022-09-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_commonmodel_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonModel',
        ),
    ]
